// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJscdLwv9jczhE_WFp0k8um4yUA7FUOg4',
    appId: '1:646456051928:web:988b6037eeffd5c52eafad',
    messagingSenderId: '646456051928',
    projectId: 'admackapizza',
    authDomain: 'admackapizza.firebaseapp.com',
    storageBucket: 'admackapizza.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC35UjvthNmZu3-HDifPfJupoNCKhgHes8',
    appId: '1:646456051928:android:898db8db58037dcb2eafad',
    messagingSenderId: '646456051928',
    projectId: 'admackapizza',
    storageBucket: 'admackapizza.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEZUWA_HFLWKL5lHUyX3FJJFJqv5H2R_w',
    appId: '1:646456051928:ios:d199ede113558f512eafad',
    messagingSenderId: '646456051928',
    projectId: 'admackapizza',
    storageBucket: 'admackapizza.firebasestorage.app',
    iosBundleId: 'com.example.ackapizzaFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEZUWA_HFLWKL5lHUyX3FJJFJqv5H2R_w',
    appId: '1:646456051928:ios:d199ede113558f512eafad',
    messagingSenderId: '646456051928',
    projectId: 'admackapizza',
    storageBucket: 'admackapizza.firebasestorage.app',
    iosBundleId: 'com.example.ackapizzaFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJscdLwv9jczhE_WFp0k8um4yUA7FUOg4',
    appId: '1:646456051928:web:3c9eea05860530372eafad',
    messagingSenderId: '646456051928',
    projectId: 'admackapizza',
    authDomain: 'admackapizza.firebaseapp.com',
    storageBucket: 'admackapizza.firebasestorage.app',
  );
}
